name: Jeremiah Park
favicon: null
layout_spectrum: 0.6815348456148058
typography_spectrum: 0.3290712155867368
title: Jeremiah Park
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.33844795310869813
  lightness: 0.1626855784561485
  saturation: 0.10443498217500746
  rhythmicContrast: 0.9384360737167299
purpose: []
